[package]
name = "zerofs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
uuid = "1.8.0"
